### ISSUE TITLE
Apparent altitude

### ISSUE THREAD

**Issue by ridlo** [ubutnux/riset-hilal#1]
Sepertinya keluaran altitude benda tidak melibatkan koreksi refraksi atmosfer ya? Walaupun namanya "apparent"? (seolah-olah tidak ada atmosfer) 

-> Sunset sunrise nya dihitung ketika altitude Matahari -0.8333.

**Comment by ridlo** [comment]
eh, bukan ternyata,
harus masukin temperatur dan tekanan sepertinya:
=> temperature_C=None, pressure_mbar='standard'

jadinya aneh, ketika ngitung sunset sunrise pakai Almanac.

**Comment by ubutnux** [comment]
Sunrise and sunset. For computational purposes, sunrise or sunset is defined to occur when the geometric zenith distance of center of the Sun is 90.8333 degrees. That is, the center of the Sun is geometrically 50 arcminutes below a horizontal plane. For an observer at sea level with a level, unobstructed horizon, under average atmospheric conditions, the upper limb of the Sun will then appear to be tangent to the horizon. The 50-arcminute geometric depression of the Sun's center used for the computations is obtained by adding the average apparent radius of the Sun (16 arcminutes) to the average amount of atmospheric refraction at the horizon (34 arcminutes).

Moonrise and moonset. Moonrise and moonset are defined similarly, but the situation is computationally more complex because of the nearness of the Moon and the eccentricity of its orbit. If the computations are carried out using coordinates of the Moon with respect to the Earth's center (the usual method), then moonrise or moonset is defined to occur when the geometric zenith distance of the center of the Moon is

90.5666 degrees + Moon's apparent angular radius - Moon's horizontal parallax
Under normal atmospheric conditions at sea level, the upper limb of the Moon will then appear to be tangent with a level, unobstructed horizon. No account is taken of the Moon's phase; that is, the Moon is always regarded as a disk in the sky and the upper limb might be dark. Here again, a constant of 34 arcminutes (0.5666 degree) is used to account for atmospheric refraction. The Moon's apparent radius varies from 15 to 17 arcminutes and its horizontal parallax varies from 54 to 61 arcminutes. Adding all the terms above together, the center of the Moon at rise or set is geometrically 5 to 10 arcminutes above the observer's "geocentric horizon" - the horizontal plane that passes through the Earth's center, orthogonal to the observer's local vertical.

Accuracy of rise/set computations. The times of rise and set phenomena cannot be precisely computed, because, in practice, the actual times depend on unpredictable atmospheric conditions that affect the amount of refraction at the horizon. Thus, even under ideal conditions (e.g., a clear sky at sea) the times computed for rise or set may be in error by a minute or more. Local topography (e.g., mountains on the horizon) and the height of the observer can affect the times of rise or set even more. It is not practical to attempt to include such effects in routine rise/set computations.

The accuracy of rise and set computations decreases at high latitudes. There, small variations in atmospheric refraction can change the time of rise or set by many minutes, since the Sun and Moon intersect the horizon at a very shallow angle. For the same reason, at high latitudes, the effects of observer height and local topography are magnified and can substantially change the times of the phenomena actually observed, or even whether the phenomena are observed to occur at all.

Twilight. There are three kinds of twilight defined: civil twilight, nautical twilight, and astronomical twilight. For computational purposes, civil twilight begins before sunrise and ends after sunset when the geometric zenith distance of the center of the Sun is 96 degrees - 6 degrees below a horizontal plane. The corresponding solar zenith distances for nautical and astronomical twilight are 102 and 108 degrees, respectively. That is, at the dark limit of nautical twilight, the center of the Sun is geometrically 12 degrees below a horizontal plane; and at the dark limit of astronomical twilight, the center of the Sun is geometrically 18 degrees below a horizontal plane.

source: http://aa.usno.navy.mil/faq/docs/RST_defs.php

**Comment by ubutnux** [comment]
> eh, bukan ternyata,
> harus masukin temperatur dan tekanan sepertinya:
> => temperature_C=None, pressure_mbar='standard'
> 
> jadinya aneh, ketika ngitung sunset sunrise pakai Almanac.

aneh bagaimana maksudnya? hasilnya sudah saya cek sama dengan nautical almanac.

**Comment by ridlo** [comment]
ketika sunset sunrise dihitung (pakai Almanac) dengan temperatur_C nya di set dengan suatu nilai (tidak None) misal 25 derajat C.

plot yang mas buat -> matahari di bawah horizon, ini karena koordinatnya (Altitude) tanpa refraksi atmosfer kan (0.833 di bawah horizon)

**Comment by ridlo** [comment]
altitudenya seolah2 tidak ada atmosfer..

**Comment by ubutnux** [comment]
> ketika sunset sunrise dihitung (pakai Almanac) dengan temperatur_C nya di set dengan suatu nilai (tidak None) misal 25 derajat C.
> 
> plot yang mas buat -> matahari di bawah horizon,ketika sunset sunrise dihitung (pakai Almanac) dengan temperatur_C nya di set dengan suatu nilai (tidak None) misal 25 derajat C.

itu kalau kita pakai plot altitud sejati, biasanya yang dipakai memang plot itu. 

> altitudenya seolah2 tidak ada atmosfer.. (padahal nilai 0.8333 itu dr efek atmosfer)
> apparentnya tidak benar2 apparent..

saya belum mengerti apa yang mau Ridlo hitung. Akan sangat membantu kalau memberikan contoh kasus dan memberikan deskripsi jelas apa yang diharapkan.

**Comment by ridlo** [comment]
ketika ada kata apparent, saya kita itu beneran altitude tampak (ada atmosfernya), sehingga plotnya harusnya matahari di horison..

Baru tahu kalau memang biasanya altitude sejati yang dipakai.

haha.. saya close saja mas..
